#文档块1
server:
  port: 8081
spring:
  profiles:
    active: prod

---
#文档块2
server:
  port: 8083
spring:
  profiles: dev

---
#文档块3
server:
  port: 8084
spring:
  profiles: prod
---
person:
  lastName: zhangsan
  age: 18
  birth: 2018/12/04
  maps: {k1: v1,k2: v2}
  objs:
   -lisi
   -zhaoliu
  dog:
    name: 小狗
    age: 8
  boss: false
